; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = 
	madhephaestus/ESP32Servo@^3.0.5
build_flags = 
	-D CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM=4
	-D CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM=8
	-D CONFIG_ESP32_WIFI_TX_BUFFER_TYPE=1
	-D CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM=16
	-D CONFIG_LWIP_MAX_SOCKETS=4
	-D CONFIG_LWIP_UDP_RECVMBOX_SIZE=4
	-D MEMP_NUM_NETBUF=4
	-D PBUF_POOL_SIZE=8
	-D CONFIG_LWIP_IPV6=0
	-D CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED=0
	-D CONFIG_ESP32_WIFI_AMSDU_TX_ENABLED=0
	-D CONFIG_LWIP_DEBUG=0
	-D CORE_DEBUG_LEVEL=0